name: Deploy AWS Lambda with Terraform

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Terraform CLI
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2 # Replace with the specific version you are using
          terraform_wrapper: false



      # 3. Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9


      # 4. Conditionally Package Dependencies for Layer
      - name: Package Dependencies for Layer
        run: |
          mkdir -p layer/python
          pip install -r requirements.txt -t layer/python
          cd layer && zip -r ../layer.zip . && cd ..

      # 5. Package Lambda Function
      - name: Package Lambda Function
        run: |
          cd src && zip -r ../function.zip . && cd ..

          
      # 6. Run Terraform to Provision Infrastructure
      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      # 7. Upload Layer to S3
      - name: Upload Layer to S3
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: |
          aws s3 cp layer.zip s3://${AWS_BUCKET}/layers/lambda-layer.zip
  
      # 8. Upload Function to S3
      - name: Upload Function to S3
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: aws s3 cp function.zip s3://${AWS_BUCKET}/functions/lambda-function.zip
          
      # 9. Update Lambda Function Code
      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name lambda-function \
            --s3-bucket ${AWS_BUCKET} \
            --s3-key functions/lambda-function.zip
